name: Prepare PR Branch

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Select the branch to copy'
        required: true
        type: string
        default: 'main'

jobs:
  copy-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source_branch }}
          fetch-depth: 0

      - name: Create and Push Copy Branch
        run: |
          NEW_BRANCH="${{ github.event.inputs.source_branch }}_for_PR"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$NEW_BRANCH"
          git push origin "$NEW_BRANCH"